#define PROJECT_VERSION_MAJOR 11
#define PROJECT_VERSION_MINOR 3
#define PROJECT_VERSION_PATCH 1
#define PROJECT_VERSION_TWEAK 0
#define PROJECT_VERSION "11.3.1.0"
#define PROJECT_VERSION_FULL "11.3.1.0-GNU"
