#define PROJECT_VERSION_MAJOR 10
#define PROJECT_VERSION_MINOR 6
#define PROJECT_VERSION_PATCH 0
#define PROJECT_VERSION_TWEAK 0
#define PROJECT_VERSION "10.6.0.0"
#define PROJECT_VERSION_FULL "10.6.0.0-GNU"
